spring:
    profiles:
    active:
    - dev
    
---
server:
    port: 8001
spring:
    profile: dev
    application:
        name: microservicecloud-dept
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloudDB01
        username: root
        password: Chnsh12Ol2012
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
eureka:
  client:
    service-url:
        defaultZone:  http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservice_dept_provider_8001
    prefer-ip-address: true
info:
  app.name: microservicecloud
  company.name: www.owen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
    port: 8001
spring:
    profile: test
    application:
        name: microservicecloud-dept
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloudDB01
        username: root
        password: Chnsh12Ol2012
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
eureka:
  client:
    service-url:
        defaultZone:  http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservice_dept_provider_8001
    prefer-ip-address: true
info:
  app.name: microservicecloud
  company.name: www.owen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$